// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 StoryEngine contributors

import { rm } from 'node:fs/promises';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import {
  aventurasDatabaseBytes,
  BLANK_PAGE,
  LANTERN_FORK,
  QUIET_HARBOUR,
  STORIES,
  STORY_TREES,
  writeAventurasBackupFolder,
} from '../import/fixtures/test-aventuras-db.js';
import { readSession, readTurns } from '../sessions/store.js';
import { makeTestServer, setUpAdmin, tempRoot, type TestServer } from '../test-server.js';

/**
 * ***Aventuras stories, through the doors*** —
 * [P13.11](../../../../docs/design/workplan/30-p13-aventuras-import.md).
 *
 * The producer's own test (`import/aventuras/story.test.ts`) proves the
 * document; these prove what a person meets: **a sweep writes no session
 * unless it is asked to** — the default this stage chose, and the reason is at
 * `SweepRequest.stories` — a sweep that is asked makes one session per story
 * through `importSession`, each row naming the session it became, and **a
 * second sweep is every story `unchanged`**, naming the same session, with no
 * copy made — whatever the conflict policy says. The server-path sweep, a
 * folder upload and a bare database upload each carry the question.
 */

let server: TestServer;
let container: string;

beforeEach(async () => {
  server = await makeTestServer();
  await setUpAdmin(server);
  container = await tempRoot('se-aventuras-stories-');
});

afterEach(async () => {
  await server.dispose();
  await rm(container, { recursive: true, force: true });
});

interface Row {
  source: string;
  disposition: string;
  objectId?: string;
  notes: { key: string; params: Record<string, unknown> }[];
}

const BOUNDARY = '----storyengineAventurasStories';

/** Every story the database holds: the two generated by the count, and the three written by hand. */
const ALL_STORIES = [...STORIES, ...STORY_TREES];

/** The four with something in them; Blank Page has nothing to make a session of. */
const WITH_ENTRIES = ALL_STORIES.filter((story) => story.id !== BLANK_PAGE.id);

async function grantFileAccess(): Promise<void> {
  const response = await server.request({
    method: 'PATCH',
    url: '/api/admin/accounts/ned',
    payload: { capabilities: { fileAccess: 'read' } },
  });
  expect(response.status, JSON.stringify(response.body)).toBe(200);
}

async function folder(): Promise<string> {
  const root = join(container, 'aventura-backup');
  await writeAventurasBackupFolder(root, { storyTrees: STORY_TREES });
  return root;
}

async function sweepFolder(
  root: string,
  extra: Record<string, unknown> = {},
): Promise<{ status: number; rows: Row[] }> {
  const response = await server.request({
    method: 'POST',
    url: '/api/import/sweep',
    payload: { root, ...extra },
  });
  return { status: response.status, rows: (response.body?.report?.items ?? []) as Row[] };
}

/** The review's row for one story. */
function storyRow(rows: readonly Row[], story: { id: string }): Row {
  const found = rows.find((row) => row.source === `aventura.db/stories/${story.id}`);
  if (found === undefined) throw new Error(`no row for ${story.id}`);
  return found;
}

async function sessionIds(): Promise<string[]> {
  const response = await server.request({ method: 'GET', url: '/api/sessions' });
  expect(response.status).toBe(200);
  return (response.body.sessions as { id: string }[]).map((session) => session.id).sort();
}

/** One field before the file, as the client's `importFile` sends `onConflict`. */
function fileWith(fields: Record<string, string>, filename: string, bytes: Uint8Array) {
  const before = Object.entries(fields).map(([name, value]) =>
    Buffer.from(
      `--${BOUNDARY}\r\nContent-Disposition: form-data; name="${name}"\r\n\r\n${value}\r\n`,
    ),
  );
  return server.request({
    method: 'POST',
    url: '/api/import/file',
    payload: Buffer.concat([
      ...before,
      Buffer.from(
        `--${BOUNDARY}\r\nContent-Disposition: form-data; name="file"; filename="${filename}"\r\n` +
          'Content-Type: application/octet-stream\r\n\r\n',
      ),
      Buffer.from(bytes),
      Buffer.from(`\r\n--${BOUNDARY}--\r\n`),
    ]),
    headers: { 'content-type': `multipart/form-data; boundary=${BOUNDARY}` },
  });
}

describe('a sweep that does not ask for stories', () => {
  it('writes no session, and says what each story holds', async () => {
    await grantFileAccess();
    const { status, rows } = await sweepFolder(await folder());

    expect(status).toBe(200);
    expect(await sessionIds()).toEqual([]);
    for (const story of ALL_STORIES) {
      const row = storyRow(rows, story);
      expect(row.disposition).toBe('recorded');
      expect(row.objectId).toBeUndefined();
      expect(row.notes.map((note) => note.key)).toEqual(['import.aventuras.storyRecorded']);
    }
    // The three tree tables are converted, so none has a row of its own.
    for (const table of ['stories', 'story_entries', 'branches']) {
      expect(rows.some((row) => row.source === `aventura.db/${table}`)).toBe(false);
    }
  });

  it('refuses a flag that is not a boolean, rather than guessing it asks', async () => {
    const response = await server.request({
      method: 'POST',
      url: '/api/import/sweep',
      payload: { root: '/nowhere', stories: 'yes' },
    });
    // The body schema refuses a word where a boolean goes, before any sweep.
    expect(response.status).toBe(400);
    expect(await sessionIds()).toEqual([]);
  });
});

describe('a sweep that asks for stories', () => {
  it('makes one session per story, each row naming it, and opens each where it was left', async () => {
    await grantFileAccess();
    const { status, rows } = await sweepFolder(await folder(), { stories: true });
    expect(status).toBe(200);

    const made = WITH_ENTRIES.map((story) => {
      const row = storyRow(rows, story);
      expect(row.disposition, JSON.stringify(row)).toBe('converted');
      expect(row.objectId).toEqual(expect.any(String));
      return row.objectId!;
    });
    expect(await sessionIds()).toEqual([...made].sort());

    // Blank Page has nothing to import, and is said to have nothing.
    const blank = storyRow(rows, BLANK_PAGE);
    expect(blank.disposition).toBe('skipped');
    expect(blank.notes.map((note) => note.key)).toEqual(['import.aventuras.storyEmpty']);

    // The Lantern Fork: ten turns, three named branches and Main, its head
    // on Tower, keyed by its row for the next sweep to find.
    const lantern = storyRow(rows, LANTERN_FORK);
    expect(lantern.notes.find((note) => note.key === 'import.aventuras.storyImported')).toEqual({
      key: 'import.aventuras.storyImported',
      params: { story: 'The Lantern Fork', turns: 10, branches: 3, mode: 'adventure' },
      level: 'info',
    });
    const session = await readSession(server.services.sessions, 'ned', lantern.objectId!);
    expect(session).toMatchObject({
      name: 'The Lantern Fork',
      origin: { source: 'import', originalFilename: `aventura.db/stories/${LANTERN_FORK.id}` },
    });
    expect(session?.branchRefs?.map((ref) => ref.name)).toEqual([
      'Main',
      'Ferry',
      'Tower',
      'Tower Stair',
    ]);
    const turns = await readTurns(server.services.sessions, 'ned', lantern.objectId!);
    expect(turns.size).toBe(10);
    const head = turns.get(session!.headTurnId!);
    expect(head?.output?.text).toBe('It catches, blue.');
    for (const turn of turns.values()) {
      expect(turn.sessionId).toBe(lantern.objectId);
      expect(turn.foreign?.source).toBe('aventuras');
      expect(turn.request).toBeUndefined();
    }

    // Quiet Harbour's narrator prompt is recorded on its row, and not carried.
    const harbour = storyRow(rows, QUIET_HARBOUR);
    expect(harbour.notes.map((note) => note.key)).toContain(
      'import.aventuras.customNarratorPrompt',
    );
    expect(
      JSON.stringify(await readSession(server.services.sessions, 'ned', harbour.objectId!)),
    ).not.toContain('Speak only in tides');
  });

  it('finds every story already here the second time, names the same session, and copies nothing', async () => {
    await grantFileAccess();
    const root = await folder();
    const first = await sweepFolder(root, { stories: true });
    const before = await sessionIds();

    // `keep-both` too: a session is never doubled, whatever the policy says.
    const second = await sweepFolder(root, { stories: true, onConflict: 'keep-both' });
    expect(second.status).toBe(200);
    for (const story of WITH_ENTRIES) {
      const row = storyRow(second.rows, story);
      expect(row.disposition).toBe('unchanged');
      expect(row.objectId).toBe(storyRow(first.rows, story).objectId);
      expect(row.notes.map((note) => note.key)).toContain('import.aventuras.storyAlreadyHere');
    }
    expect(await sessionIds()).toEqual(before);
  });

  it('names the session in the import ledger, so the review can be found from it', async () => {
    await grantFileAccess();
    const { rows } = await sweepFolder(await folder(), { stories: true });
    const sessionId = storyRow(rows, LANTERN_FORK).objectId!;

    const response = await server.request({
      method: 'GET',
      url: `/api/import/objects/${sessionId}/notes`,
    });
    expect(response.status).toBe(200);
    expect(JSON.stringify(response.body)).toContain('import.aventuras.forkSplitPair');
  });
});

describe('the other doors carry the question', () => {
  it('a bare database upload asks with a field before the file, and is unchanged the second time', async () => {
    const bytes = await aventurasDatabaseBytes({ storyTrees: STORY_TREES });

    const unasked = await fileWith({}, 'library.db', bytes);
    expect(unasked.status, JSON.stringify(unasked.body)).toBeLessThan(300);
    expect(await sessionIds()).toEqual([]);

    const asked = await fileWith({ stories: 'true' }, 'library.db', bytes);
    const rows = (asked.body.report?.items ?? []) as Row[];
    expect(storyRow(rows, LANTERN_FORK).disposition).toBe('converted');
    expect(await sessionIds()).toHaveLength(WITH_ENTRIES.length);

    const again = await fileWith({ stories: 'true' }, 'library.db', bytes);
    const second = (again.body.report?.items ?? []) as Row[];
    for (const story of WITH_ENTRIES) {
      expect(storyRow(second, story).disposition).toBe('unchanged');
    }
    expect(await sessionIds()).toHaveLength(WITH_ENTRIES.length);
  });

  it('a folder upload asks with a field beside the manifest', async () => {
    const bytes = await aventurasDatabaseBytes({ storyTrees: STORY_TREES });
    const parts = [
      Buffer.from(
        `--${BOUNDARY}\r\nContent-Disposition: form-data; name="stories"\r\n\r\ntrue\r\n` +
          `--${BOUNDARY}\r\nContent-Disposition: form-data; name="aventura.db"; filename="aventura.db"\r\n` +
          'Content-Type: application/octet-stream\r\n\r\n',
      ),
      Buffer.from(bytes),
      Buffer.from(
        `\r\n--${BOUNDARY}\r\nContent-Disposition: form-data; name="manifest"\r\n\r\n` +
          `${JSON.stringify(['aventura.db'])}\r\n--${BOUNDARY}--\r\n`,
      ),
    ];
    const response = await server.request({
      method: 'POST',
      url: '/api/import/directory',
      payload: Buffer.concat(parts),
      headers: { 'content-type': `multipart/form-data; boundary=${BOUNDARY}` },
    });
    expect(response.status, JSON.stringify(response.body)).toBe(200);
    const rows = response.body.report.items as Row[];
    expect(storyRow(rows, QUIET_HARBOUR).disposition).toBe('converted');
    expect(await sessionIds()).toHaveLength(WITH_ENTRIES.length);
  });
});
