// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 StoryEngine contributors

import { createHash } from 'node:crypto';
import { readdir, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';

import { DatabaseSync } from 'node:sqlite';

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { ACTOR_SCHEMA, LOREBOOK_SCHEMA, type Actor, type Lorebook } from '@storyengine/shared';

import { read } from '../library.js';
import { sessionAssetsRoot } from '../renditions/store.js';
import { pixelBytes } from '../storage/card/test-png.js';
import {
  aventurasDatabaseBytes,
  BLANK_PAGE,
  CHAPTER_SUMMARY_MARK,
  FIXTURE_PICTURES,
  FIXTURE_PORTRAITS,
  LANTERN_FORK,
  QUIET_HARBOUR,
  STORIES,
  STORY_TREES,
  writeAventurasBackupFolder,
} from '../import/fixtures/test-aventuras-db.js';
import { readSession, readTurns } from '../sessions/store.js';
import {
  makeTestServer,
  ownObjects,
  setUpAdmin,
  tempRoot,
  type TestServer,
} from '../test-server.js';

/**
 * ***Aventuras stories, through the doors*** —
 * [P13.11](../../../../docs/design/workplan/30-p13-aventuras-import.md).
 *
 * The producer's own test (`import/aventuras/story.test.ts`) proves the
 * document; these prove what a person meets: **a sweep writes no session
 * unless it is asked to** — the default this stage chose, and the reason is at
 * `SweepRequest.stories` — a sweep that is asked makes one session per story
 * through `importSession`, each row naming the session it became, and **a
 * second sweep is every story `unchanged`**, naming the same session, with no
 * copy made — whatever the conflict policy says. The server-path sweep, a
 * folder upload and a bare database upload each carry the question.
 */

let server: TestServer;
let container: string;

beforeEach(async () => {
  server = await makeTestServer();
  await setUpAdmin(server);
  container = await tempRoot('se-aventuras-stories-');
});

afterEach(async () => {
  await server.dispose();
  await rm(container, { recursive: true, force: true });
});

interface Row {
  source: string;
  disposition: string;
  objectId?: string;
  alsoProduced?: string[];
  notes: { key: string; params: Record<string, unknown> }[];
}

const BOUNDARY = '----storyengineAventurasStories';

/** Every story the database holds: the two generated by the count, and the three written by hand. */
const ALL_STORIES = [...STORIES, ...STORY_TREES];

/** The four with something in them; Blank Page has nothing to make a session of. */
const WITH_ENTRIES = ALL_STORIES.filter((story) => story.id !== BLANK_PAGE.id);

async function grantFileAccess(): Promise<void> {
  const response = await server.request({
    method: 'PATCH',
    url: '/api/admin/accounts/ned',
    payload: { capabilities: { fileAccess: 'read' } },
  });
  expect(response.status, JSON.stringify(response.body)).toBe(200);
}

async function folder(): Promise<string> {
  const root = join(container, 'aventura-backup');
  await writeAventurasBackupFolder(root, { storyTrees: STORY_TREES });
  return root;
}

async function sweepFolder(
  root: string,
  extra: Record<string, unknown> = {},
): Promise<{ status: number; rows: Row[] }> {
  const response = await server.request({
    method: 'POST',
    url: '/api/import/sweep',
    payload: { root, ...extra },
  });
  return { status: response.status, rows: (response.body?.report?.items ?? []) as Row[] };
}

/** The review's row for one story. */
function storyRow(rows: readonly Row[], story: { id: string }): Row {
  const found = rows.find((row) => row.source === `aventura.db/stories/${story.id}`);
  if (found === undefined) throw new Error(`no row for ${story.id}`);
  return found;
}

async function sessionIds(): Promise<string[]> {
  const response = await server.request({ method: 'GET', url: '/api/sessions' });
  expect(response.status).toBe(200);
  return (response.body.sessions as { id: string }[]).map((session) => session.id).sort();
}

/** One field before the file, as the client's `importFile` sends `onConflict`. */
function fileWith(fields: Record<string, string>, filename: string, bytes: Uint8Array) {
  const before = Object.entries(fields).map(([name, value]) =>
    Buffer.from(
      `--${BOUNDARY}\r\nContent-Disposition: form-data; name="${name}"\r\n\r\n${value}\r\n`,
    ),
  );
  return server.request({
    method: 'POST',
    url: '/api/import/file',
    payload: Buffer.concat([
      ...before,
      Buffer.from(
        `--${BOUNDARY}\r\nContent-Disposition: form-data; name="file"; filename="${filename}"\r\n` +
          'Content-Type: application/octet-stream\r\n\r\n',
      ),
      Buffer.from(bytes),
      Buffer.from(`\r\n--${BOUNDARY}--\r\n`),
    ]),
    headers: { 'content-type': `multipart/form-data; boundary=${BOUNDARY}` },
  });
}

describe('a sweep that does not ask for stories', () => {
  it('writes no session, and says what each story holds', async () => {
    await grantFileAccess();
    const { status, rows } = await sweepFolder(await folder());

    expect(status).toBe(200);
    expect(await sessionIds()).toEqual([]);
    for (const story of ALL_STORIES) {
      const row = storyRow(rows, story);
      expect(row.disposition).toBe('recorded');
      expect(row.objectId).toBeUndefined();
      expect(row.notes.map((note) => note.key)).toEqual(['import.aventuras.storyRecorded']);
    }
    // The three tree tables are converted, so none has a row of its own.
    for (const table of ['stories', 'story_entries', 'branches']) {
      expect(rows.some((row) => row.source === `aventura.db/${table}`)).toBe(false);
    }
  });

  it('refuses a flag that is not a boolean, rather than guessing it asks', async () => {
    const response = await server.request({
      method: 'POST',
      url: '/api/import/sweep',
      payload: { root: '/nowhere', stories: 'yes' },
    });
    // The body schema refuses a word where a boolean goes, before any sweep.
    expect(response.status).toBe(400);
    expect(await sessionIds()).toEqual([]);
  });
});

describe('a sweep that asks for stories', () => {
  it('makes one session per story, each row naming it, and opens each where it was left', async () => {
    await grantFileAccess();
    const { status, rows } = await sweepFolder(await folder(), { stories: true });
    expect(status).toBe(200);

    const made = WITH_ENTRIES.map((story) => {
      const row = storyRow(rows, story);
      expect(row.disposition, JSON.stringify(row)).toBe('converted');
      expect(row.objectId).toEqual(expect.any(String));
      return row.objectId!;
    });
    expect(await sessionIds()).toEqual([...made].sort());

    // Blank Page has nothing to import, and is said to have nothing.
    const blank = storyRow(rows, BLANK_PAGE);
    expect(blank.disposition).toBe('skipped');
    expect(blank.notes.map((note) => note.key)).toEqual(['import.aventuras.storyEmpty']);

    // The Lantern Fork: ten turns, three named branches and Main, its head
    // on Tower, keyed by its row for the next sweep to find.
    const lantern = storyRow(rows, LANTERN_FORK);
    expect(lantern.notes.find((note) => note.key === 'import.aventuras.storyImported')).toEqual({
      key: 'import.aventuras.storyImported',
      params: { story: 'The Lantern Fork', turns: 10, branches: 3, mode: 'adventure' },
      level: 'info',
    });
    const session = await readSession(server.services.sessions, 'ned', lantern.objectId!);
    expect(session).toMatchObject({
      name: 'The Lantern Fork',
      origin: { source: 'import', originalFilename: `aventura.db/stories/${LANTERN_FORK.id}` },
    });
    expect(session?.branchRefs?.map((ref) => ref.name)).toEqual([
      'Main',
      'Ferry',
      'Tower',
      'Tower Stair',
    ]);
    const turns = await readTurns(server.services.sessions, 'ned', lantern.objectId!);
    expect(turns.size).toBe(10);
    const head = turns.get(session!.headTurnId!);
    expect(head?.output?.text).toBe('It catches, blue.');
    for (const turn of turns.values()) {
      expect(turn.sessionId).toBe(lantern.objectId);
      expect(turn.foreign?.source).toBe('aventuras');
      expect(turn.request).toBeUndefined();
    }

    // Quiet Harbour's narrator prompt is recorded on its row, and not carried.
    const harbour = storyRow(rows, QUIET_HARBOUR);
    expect(harbour.notes.map((note) => note.key)).toContain(
      'import.aventuras.customNarratorPrompt',
    );
    expect(
      JSON.stringify(await readSession(server.services.sessions, 'ned', harbour.objectId!)),
    ).not.toContain('Speak only in tides');
  });

  it('finds every story already here the second time, names the same session, and copies nothing', async () => {
    await grantFileAccess();
    const root = await folder();
    const first = await sweepFolder(root, { stories: true });
    const before = await sessionIds();

    // `keep-both` too: a session is never doubled, whatever the policy says.
    const second = await sweepFolder(root, { stories: true, onConflict: 'keep-both' });
    expect(second.status).toBe(200);
    for (const story of WITH_ENTRIES) {
      const row = storyRow(second.rows, story);
      expect(row.disposition).toBe('unchanged');
      expect(row.objectId).toBe(storyRow(first.rows, story).objectId);
      expect(row.notes.map((note) => note.key)).toContain('import.aventuras.storyAlreadyHere');
    }
    expect(await sessionIds()).toEqual(before);
  });

  it('names the session in the import ledger, so the review can be found from it', async () => {
    await grantFileAccess();
    const { rows } = await sweepFolder(await folder(), { stories: true });
    const sessionId = storyRow(rows, LANTERN_FORK).objectId!;

    const response = await server.request({
      method: 'GET',
      url: `/api/import/objects/${sessionId}/notes`,
    });
    expect(response.status).toBe(200);
    expect(JSON.stringify(response.body)).toContain('import.aventuras.forkSplitPair');
  });
});

describe('the other doors carry the question', () => {
  it('a bare database upload asks with a field before the file, and is unchanged the second time', async () => {
    const bytes = await aventurasDatabaseBytes({ storyTrees: STORY_TREES });

    const unasked = await fileWith({}, 'library.db', bytes);
    expect(unasked.status, JSON.stringify(unasked.body)).toBeLessThan(300);
    expect(await sessionIds()).toEqual([]);

    const asked = await fileWith({ stories: 'true' }, 'library.db', bytes);
    const rows = (asked.body.report?.items ?? []) as Row[];
    expect(storyRow(rows, LANTERN_FORK).disposition).toBe('converted');
    expect(await sessionIds()).toHaveLength(WITH_ENTRIES.length);

    const again = await fileWith({ stories: 'true' }, 'library.db', bytes);
    const second = (again.body.report?.items ?? []) as Row[];
    for (const story of WITH_ENTRIES) {
      expect(storyRow(second, story).disposition).toBe('unchanged');
    }
    expect(await sessionIds()).toHaveLength(WITH_ENTRIES.length);
  });

  it('a folder upload asks with a field beside the manifest', async () => {
    const bytes = await aventurasDatabaseBytes({ storyTrees: STORY_TREES });
    const parts = [
      Buffer.from(
        `--${BOUNDARY}\r\nContent-Disposition: form-data; name="stories"\r\n\r\ntrue\r\n` +
          `--${BOUNDARY}\r\nContent-Disposition: form-data; name="aventura.db"; filename="aventura.db"\r\n` +
          'Content-Type: application/octet-stream\r\n\r\n',
      ),
      Buffer.from(bytes),
      Buffer.from(
        `\r\n--${BOUNDARY}\r\nContent-Disposition: form-data; name="manifest"\r\n\r\n` +
          `${JSON.stringify(['aventura.db'])}\r\n--${BOUNDARY}--\r\n`,
      ),
    ];
    const response = await server.request({
      method: 'POST',
      url: '/api/import/directory',
      payload: Buffer.concat(parts),
      headers: { 'content-type': `multipart/form-data; boundary=${BOUNDARY}` },
    });
    expect(response.status, JSON.stringify(response.body)).toBe(200);
    const rows = response.body.report.items as Row[];
    expect(storyRow(rows, QUIET_HARBOUR).disposition).toBe('converted');
    expect(await sessionIds()).toHaveLength(WITH_ENTRIES.length);
  });
});

describe('a story’s world', () => {
  /**
   * ***P13.12*** — the head branch's characters as the session's cast and
   * its entries, places, things and beats as one lorebook of its own, written
   * before the session so its links hold (`requireLinks`), and named on the
   * story's row. The resolution and the mapping are `world.test.ts`'s; these
   * are what a person meets: the session plays with them, and a second sweep
   * leaves every one of them as it was.
   */
  const LANTERN_KEY = `aventura.db/stories/${LANTERN_FORK.id}`;

  async function history(kind: string, id: string): Promise<number> {
    const response = await server.request({
      method: 'GET',
      url: `/api/library/${kind}/${id}/history`,
    });
    expect(response.status).toBe(200);
    return (response.body as { versions: unknown[] }).versions.length;
  }

  it('links the head’s cast and the story’s lorebook from the session, each keyed for re-import', async () => {
    await grantFileAccess();
    const { rows } = await sweepFolder(await folder(), { stories: true });
    const lantern = storyRow(rows, LANTERN_FORK);
    expect(lantern.disposition, JSON.stringify(lantern)).toBe('converted');

    const session = await readSession(server.services.sessions, 'ned', lantern.objectId!);
    const persona = session?.cast?.persona ?? '';
    const actors = session?.cast?.actors ?? [];
    const lore = session?.lore ?? [];
    expect(actors).toHaveLength(1);
    expect(lore).toHaveLength(1);
    // Every object the session links is named on the row, so the review is
    // findable from each (`alsoProduced`), and nothing else is.
    expect([...(lantern.alsoProduced ?? [])].sort()).toEqual([persona, ...actors, ...lore].sort());

    // Mara, the protagonist, is the persona, with her PNG portrait as her card.
    const mara = read(server.services.library, 'ned', persona, ACTOR_SCHEMA);
    expect((mara.body as Actor).name).toBe('Mara');
    expect((mara.body as Actor).roles).toEqual(['persona']);
    expect((mara.body as Actor).provenance.originalFilename).toBe(
      `${LANTERN_KEY}/characters/lf-c-mara`,
    );
    expect(pixelBytes(new Uint8Array(await readFile(mara.path)))).toEqual(
      pixelBytes(FIXTURE_PORTRAITS.png),
    );
    // The Keeper is Tower's edit of him; the Gull, deleted on Tower, is not here.
    const keeper = read(server.services.library, 'ned', actors[0]!, ACTOR_SCHEMA).body as Actor;
    expect(keeper.name).toBe('The Drowned Keeper');
    expect(keeper.provenance.originalFilename).toBe(`${LANTERN_KEY}/characters/lf-c-keeper`);
    const names = (await ownObjects(server, 'actors')).objects.map((one) => one['name']);
    expect(names).not.toContain('Gull');

    // One book, of the story's own, with every kind in it — and not Ferry's dock.
    const book = read(server.services.library, 'ned', lore[0]!, LOREBOOK_SCHEMA).body as Lorebook;
    expect(book.provenance.originalFilename).toBe(`${LANTERN_KEY}/lorebook`);
    expect(book.entries.map((entry) => entry.tag).sort()).toEqual(
      ['faction', 'item', 'item', 'item', 'location', 'location', 'location', 'story-beat'].sort(),
    );
    expect(JSON.stringify(book)).not.toContain('Ferry Dock');

    const said = lantern.notes.map((note) => note.key);
    expect(said).toEqual(
      expect.arrayContaining([
        'import.aventuras.storyImported',
        'import.aventuras.storyWorld',
        'import.aventuras.storyPersona',
        'import.aventuras.storyBeatsAsLore',
        'import.aventuras.worldBranchesDiffer',
      ]),
    );
    expect(
      lantern.notes.find((note) => note.key === 'import.aventuras.storyWorld')?.params,
    ).toEqual({
      story: 'The Lantern Fork',
      characters: 2,
      lore: 2,
      locations: 2,
      items: 3,
      beats: 1,
    });

    // A story with no world links none, and says nothing of one.
    const harbour = storyRow(rows, QUIET_HARBOUR);
    const quiet = await readSession(server.services.sessions, 'ned', harbour.objectId!);
    expect(quiet?.cast).toBeUndefined();
    expect(quiet?.lore).toBeUndefined();
    expect(harbour.alsoProduced).toBeUndefined();
    expect(harbour.notes.map((note) => note.key)).not.toContain('import.aventuras.storyWorld');
  });

  it('leaves every actor and book as it was on a second sweep, with no new version of any', async () => {
    await grantFileAccess();
    const root = await folder();
    const first = await sweepFolder(root, { stories: true });
    const lantern = storyRow(first.rows, LANTERN_FORK);
    const session = await readSession(server.services.sessions, 'ned', lantern.objectId!);
    const actorIds = [session!.cast!.persona!, ...session!.cast!.actors];
    const bookId = session!.lore![0]!;

    const before = {
      actors: await ownObjects(server, 'actors'),
      lorebooks: await ownObjects(server, 'lorebooks'),
      hashes: [
        ...actorIds.map((id) => read(server.services.library, 'ned', id, ACTOR_SCHEMA).contentHash),
        read(server.services.library, 'ned', bookId, LOREBOOK_SCHEMA).contentHash,
      ],
      versions: [
        ...(await Promise.all(actorIds.map((id) => history('actors', id)))),
        await history('lorebooks', bookId),
      ],
    };

    // `replace`, the policy that would rewrite them if anything did.
    const second = await sweepFolder(root, { stories: true, onConflict: 'replace' });
    expect(second.status).toBe(200);
    for (const story of WITH_ENTRIES) {
      const row = storyRow(second.rows, story);
      expect(row.disposition).toBe('unchanged');
      // The row names what the session here already links to.
      expect([...(row.alsoProduced ?? [])].sort()).toEqual(
        [...(storyRow(first.rows, story).alsoProduced ?? [])].sort(),
      );
    }
    expect(await ownObjects(server, 'actors')).toEqual(before.actors);
    expect(await ownObjects(server, 'lorebooks')).toEqual(before.lorebooks);
    expect([
      ...actorIds.map((id) => read(server.services.library, 'ned', id, ACTOR_SCHEMA).contentHash),
      read(server.services.library, 'ned', bookId, LOREBOOK_SCHEMA).contentHash,
    ]).toEqual(before.hashes);
    expect([
      ...(await Promise.all(actorIds.map((id) => history('actors', id)))),
      await history('lorebooks', bookId),
    ]).toEqual(before.versions);
  });

  it('finds the world it made when a deleted session’s story is swept again, and changes none of it', async () => {
    await grantFileAccess();
    const root = await folder();
    const first = await sweepFolder(root, { stories: true });
    const lantern = storyRow(first.rows, LANTERN_FORK);
    const deleted = await server.request({
      method: 'DELETE',
      url: `/api/sessions/${lantern.objectId!}`,
    });
    expect(deleted.status, JSON.stringify(deleted.body)).toBeLessThan(300);
    const actorsBefore = await ownObjects(server, 'actors');

    // The trash has no index row, so the key no longer finds a session
    // ([P13 §0.5]'s trash item) — and the turn ids would; so this is the one
    // road on which the world is written a second time, and it must settle on
    // the objects the first sweep made rather than beside them.
    const second = await sweepFolder(root, { stories: true });
    const again = storyRow(second.rows, LANTERN_FORK);
    expect([...(again.alsoProduced ?? [])].sort()).toEqual(
      [...(lantern.alsoProduced ?? [])].sort(),
    );
    const keys = again.notes.map((note) => note.key);
    expect(keys.filter((key) => key === 'import.object.unchanged')).toHaveLength(3);
    expect(keys).not.toContain('import.object.replaced');
    expect(await ownObjects(server, 'actors')).toEqual(actorsBefore);
  });
});

describe('a story’s pictures', () => {
  /**
   * ***P13.13*** — each picture a finished rendition beside the turns,
   * written by `importSession` into the session it made, and served by the
   * rendition routes as any other. The mapping, the bound and the refusal are
   * `import/aventuras/pictures.test.ts`'s; these are what a person meets: the
   * pictures listed and their bytes served, the row saying what came and
   * what did not, no job for any of them, and a second sweep that writes
   * nothing.
   */
  interface Listed {
    id: string;
    turnId: string;
    purpose: string;
    state: string;
    asset: { mime: string; bytes: number; digest: string } | null;
    foreign?: { source: string; id: string };
  }

  async function listed(sessionId: string): Promise<Listed[]> {
    const response = await server.request({
      method: 'GET',
      url: `/api/sessions/${sessionId}/renditions`,
    });
    expect(response.status).toBe(200);
    return response.body.renditions as Listed[];
  }

  it('lists every picture that came, serves its bytes, and queues no job for any', async () => {
    await grantFileAccess();
    const { rows } = await sweepFolder(await folder(), { stories: true });
    const lantern = storyRow(rows, LANTERN_FORK);
    expect(lantern.disposition, JSON.stringify(lantern)).toBe('converted');

    const said = new Map(lantern.notes.map((note) => [note.key, note.params]));
    expect(said.get('import.aventuras.storyPictures')).toEqual({
      story: 'The Lantern Fork',
      illustrations: 6,
      backgrounds: 2,
    });
    for (const key of [
      'import.aventuras.picturesUnfinished',
      'import.aventuras.picturesUnplaced',
      'import.aventuras.checkpointBackgrounds',
      'import.aventuras.pictureUnreadable',
      'import.aventuras.pictureModels',
    ]) {
      expect(said.get(key), key).toMatchObject({ story: 'The Lantern Fork' });
    }
    // Its pictures came, so what is left behind is its chapters alone
    // (P13.14's, recorded — `a story’s chapters`, below).
    expect(said.get('import.aventuras.storyWorldRecorded')).toEqual({
      story: 'The Lantern Fork',
      chapters: 2,
      checkpoints: 0,
    });

    const pictures = await listed(lantern.objectId!);
    expect(pictures).toHaveLength(8);
    expect(pictures.filter((one) => one.purpose === 'background')).toHaveLength(2);
    for (const picture of pictures) {
      expect(picture.state).toBe('ready');
      expect(picture.foreign?.source).toBe('aventuras');
    }

    // The head's line: the Tower backdrop and the head's picture, on the head.
    const session = await readSession(server.services.sessions, 'ned', lantern.objectId!);
    const onHead = pictures.filter((one) => one.turnId === session?.headTurnId);
    expect(onHead.map((one) => one.foreign?.id).sort()).toEqual(['lf-bg-tower', 'lf-p-large']);

    // Served as the route serves any rendition: its type, its digest, its bytes.
    const ferry = pictures.find((one) => one.foreign?.id === 'lf-p-ferry')!;
    const served = await server.request({
      method: 'GET',
      url: `/api/sessions/${lantern.objectId!}/renditions/${encodeURIComponent(ferry.id)}/asset`,
    });
    expect(served.status).toBe(200);
    expect(served.headers['content-type']).toBe('image/webp');
    expect(served.headers['etag']).toBe(
      `sha256:${createHash('sha256').update(FIXTURE_PICTURES.ferry).digest('hex')}`,
    );
    expect(Number(served.headers['content-length'])).toBe(FIXTURE_PICTURES.ferry.byteLength);

    // Finished records, never jobs.
    const jobs = server.services.state.db
      .prepare('select count(*) as n from rendition_job')
      .get() as { n: unknown };
    expect(Number(jobs.n)).toBe(0);

    // A story generated by the count has pictures Aventuras never finished:
    // said, and the rest of it imported.
    const bell = storyRow(rows, STORIES[0]!);
    expect(bell.disposition).toBe('converted');
    expect(bell.notes.map((note) => note.key)).toContain('import.aventuras.picturesUnfinished');
    expect(
      bell.notes.find((note) => note.key === 'import.aventuras.storyWorldRecorded')?.params,
    ).toEqual({ story: STORIES[0]!.title, chapters: 1, checkpoints: 1 });
  });

  it('writes no picture a second time, and leaves the first as it was', async () => {
    await grantFileAccess();
    const root = await folder();
    const first = await sweepFolder(root, { stories: true });
    const sessionId = storyRow(first.rows, LANTERN_FORK).objectId!;
    const assets = sessionAssetsRoot(server.services.sessions.layout, 'ned', sessionId);
    const before = { listed: await listed(sessionId), files: (await readdir(assets)).sort() };
    expect(before.files).toHaveLength(8);

    const second = await sweepFolder(root, { stories: true, onConflict: 'replace' });
    const row = storyRow(second.rows, LANTERN_FORK);
    expect(row.disposition).toBe('unchanged');
    expect(row.notes.map((note) => note.key)).not.toContain('import.aventuras.storyPictures');
    expect(await listed(sessionId)).toEqual(before.listed);
    expect((await readdir(assets)).sort()).toEqual(before.files);
  });
});

describe('a story’s chapters', () => {
  /**
   * ***Recorded, and why*** — P13.14. An Aventuras chapter is a summary its
   * own model wrote of a stretch of entries, and the one place this engine
   * keeps a summary of a session is P8's rolling chain: a content-addressed
   * cache under `sessions/<id>/summaries/`, each link's key the hash of *this*
   * install's summariser and the turns it covers (`sessions/summary-chain.ts`).
   * A foreign summary has no key it could honestly be filed under — ours
   * would serve it as a summary we wrote, and any other would never be looked
   * up — and every turn it summarised came across, so the chain writes its own.
   * So the summaries stay in Aventuras, and these hold the three things that
   * decision owes: the row says so, nothing of a summary reaches the session,
   * and the reader never so much as selects one.
   */
  async function filesUnder(root: string): Promise<string[]> {
    return (await readdir(root, { recursive: true, withFileTypes: true }))
      .filter((entry) => entry.isFile())
      .map((entry) => join(entry.parentPath, entry.name))
      .sort();
  }

  it('says they stayed in Aventuras, and writes none of a summary anywhere', async () => {
    await grantFileAccess();
    const root = await folder();

    const prepare = vi.spyOn(DatabaseSync.prototype, 'prepare');
    let statements: string[];
    let first: Awaited<ReturnType<typeof sweepFolder>>;
    try {
      first = await sweepFolder(root, { stories: true });
      statements = prepare.mock.calls.map(([sql]) => sql);
    } finally {
      prepare.mockRestore();
    }

    // The row: imported, with its two chapters — main's and Tower's — named
    // as what stayed behind.
    const lantern = storyRow(first.rows, LANTERN_FORK);
    expect(lantern.disposition).toBe('converted');
    expect(
      lantern.notes.find((note) => note.key === 'import.aventuras.storyWorldRecorded')?.params,
    ).toEqual({ story: 'The Lantern Fork', chapters: 2, checkpoints: 0 });

    // Counted, and read by no statement: a summary cannot leak from a column
    // nothing selects.
    const touching = statements.filter((sql) => /chapters/i.test(sql));
    expect(touching.length).toBeGreaterThan(0);
    for (const sql of touching) expect(sql, sql).toMatch(/count\(\*\)/i);
    expect(statements.some((sql) => /summary/i.test(sql))).toBe(false);

    // Nothing of a summary in the session, and no summary store seeded.
    const sessionRoot = server.services.sessions.layout.sessionRoot('ned', lantern.objectId!);
    const files = await filesUnder(sessionRoot);
    expect(files.some((path) => /[\\/]summaries[\\/]/.test(path))).toBe(false);
    for (const path of files) {
      expect((await readFile(path)).includes(CHAPTER_SUMMARY_MARK), path).toBe(false);
    }
    expect(JSON.stringify(first.rows)).not.toContain(CHAPTER_SUMMARY_MARK);

    // And a second sweep writes nothing: the story is already here.
    const second = await sweepFolder(root, { stories: true, onConflict: 'replace' });
    expect(storyRow(second.rows, LANTERN_FORK).disposition).toBe('unchanged');
    expect(await filesUnder(sessionRoot)).toEqual(files);
  });
});
