// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 StoryEngine contributors

import { versionName } from './version.js';

/**
 * `CHANGELOG.md`, read as releases rather than as a string.
 *
 * **The heading grammar was already a contract before this file existed**,
 * which is the whole reason the reader belongs here and not in the client.
 * `.github/workflows/release.yml` greps `^## ${version}` to refuse a tag with
 * no entry; `tools/release.test.ts` asserts the same line against
 * `package.json`; and `version.test.ts` parses the heading's two other fields
 * to hold the typed name to [`versionName`]. Three spellings of one grammar,
 * and the home page would have been a fourth. [version.ts]'s own docstring
 * argued the case in advance — *"a rule about the project's own version belongs
 * beside the schemas everything else is built against"* — and a release heading
 * is a version with a name and a date after it.
 *
 * It costs this package nothing it has not already paid. `index.ts` promises
 * *"no runtime dependency beyond the schema library and its validator"*, and
 * this takes a string and returns objects: no `node:fs`, no knowledge of where
 * the file is, and nothing to stop the client bundling it.
 *
 * **What it deliberately does not do is check the name.** A heading types the
 * version and the name side by side, and the guarantee that the second is what
 * the first yields is `changelog.test.ts`'s, asserted against the real file in
 * CI. Enforcing it here would mean a typo in one heading blanking the arrival
 * page of a build that had already shipped — the wrong place to be strict,
 * because the reader cannot do anything about it and the author already has.
 */

export interface ChangelogRelease {
  /** The semver string the heading opens with, exactly as typed. */
  version: string;
  /**
   * The name typed beside it — *1.0-alpha 4*. Recorded as found rather than
   * derived from {@link versionName}, so that a disagreement between the two is
   * something a test can see rather than something this function hides.
   */
  name: string;
  /**
   * `YYYY-MM-DD`, as typed. **A calendar date, not an instant** — there is no
   * time and no zone in a release heading, and rendering it as though there
   * were is how it lands on the wrong day. The client's `formatCalendarDate`
   * carries that argument.
   */
  date: string;
  /** Everything under the heading up to the next one, verbatim and trimmed. */
  body: string;
}

export interface Changelog {
  /** The text of the opening `# ` heading, or `null` if the file has none. */
  title: string | null;
  /** Everything between the title and the first release, verbatim and trimmed. */
  preamble: string;
  /**
   * **File order, which is newest first, and is not re-sorted here.**
   *
   * Sorting would mean this function deciding which of two versions is later,
   * and that comparison already exists once — `compareVersions`, on the server
   * side of the boundary, where the update check needs it. A second ordering
   * that could disagree with the file is worse than trusting the file, and the
   * file is generated by a release process that appends to the top.
   */
  releases: readonly ChangelogRelease[];
  /**
   * `##` lines the grammar refused, as they appear.
   *
   * **Empty today, and a test asserts that it stays empty** — which is the
   * point of recording them rather than dropping them. The case this is waiting
   * for is an `## Unreleased` section: a heading with no version and no date
   * that a running build has no business showing, because *this build's
   * changelog* means the releases the build was cut from. A red test there asks
   * for that decision instead of letting a blank row appear on the arrival page
   * and be discovered later.
   *
   * A refused line is not removed from the document: it stays in the body of
   * whatever release it fell inside, so nothing silently vanishes from the
   * screen while the question is open.
   */
  unrecognised: readonly string[];
}

/**
 * The heading's three fields, separated by a spaced em dash — the separator
 * `CHANGELOG.md`'s own preamble documents: *"A heading here opens with the
 * string, because the release workflow reads it there, and carries the name and
 * the date after it."*
 *
 * A name may hold spaces (*1.0-beta 1.1*) but never the separator, so an exact
 * three-way split is the recogniser rather than a lenient one.
 */
const SEPARATOR = ' — ';

/** A calendar date and nothing else — no time, no zone, no `Z`. */
const DATE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * A `## ` line read as a release heading, or `null` when it is not one.
 *
 * **{@link versionName} is used as a recogniser here, not as a generator**, and
 * that is what makes the refusals consistent with the rest of the project: its
 * docstring's *"`null` for anything outside the scheme, rather than a guess"*
 * becomes *"not a release, rather than a guessed one"*. `## Unreleased`,
 * `## v1.0.0 — … — …` and `## 1.0.0-alpha — … — …` are each refused by that one
 * rule, so the set of things this accepts is exactly the set
 * [releases §7.1](../../../docs/design/workplan/04-repo-and-releases.md) defines.
 */
function readHeading(line: string): { version: string; name: string; date: string } | null {
  const fields = line.slice('## '.length).trim().split(SEPARATOR);
  if (fields.length !== 3) return null;
  const version = fields[0] ?? '';
  const name = fields[1] ?? '';
  const date = fields[2] ?? '';
  if (versionName(version) === null) return null;
  if (!DATE.test(date)) return null;
  if (name === '') return null;
  return { version, name, date };
}

export function parseChangelog(source: string): Changelog {
  // **Line granularity, with no requirement of a blank line before a heading.**
  // `CHANGELOG.md` has already been written with a bullet on the line directly
  // above `## 1.0.0-alpha.3`, and a splitter keyed on a blank line would have
  // swallowed a whole release without failing anything. Markdown does not
  // require the blank line either, so the file is right and the lenient reader
  // is the correct one rather than the forgiving one.
  const lines = source.split('\n');
  const releases: ChangelogRelease[] = [];
  const unrecognised: string[] = [];
  const preamble: string[] = [];

  let title: string | null = null;
  // The release currently being accumulated, and the lines it has collected.
  // `null` means we are still above the first heading, where lines go to the
  // preamble instead.
  let open: { version: string; name: string; date: string } | null = null;
  let body: string[] = [];

  function close(): void {
    if (open === null) return;
    releases.push({ ...open, body: body.join('\n').trim() });
    body = [];
  }

  for (const line of lines) {
    if (title === null && open === null && line.startsWith('# ')) {
      title = line.slice('# '.length).trim();
      continue;
    }
    if (line.startsWith('## ')) {
      const heading = readHeading(line);
      if (heading === null) {
        // Refused, and kept: the line stays in the text it fell inside so the
        // document a reader sees is still the document that was written.
        unrecognised.push(line);
        (open === null ? preamble : body).push(line);
        continue;
      }
      close();
      open = heading;
      continue;
    }
    (open === null ? preamble : body).push(line);
  }
  close();

  return { title, preamble: preamble.join('\n').trim(), releases, unrecognised };
}

/**
 * One release by its version string, or `undefined` when this changelog has no
 * such release.
 *
 * **`undefined` rather than a fallback**, because the two callers want to say
 * different things about the same absence: the arrival page shows the newest
 * release *and says that the address named one it does not have*, while the
 * workbench's list marks the newest row as current. Baking the fallback in here
 * would leave neither able to tell the difference. They share this function so
 * that the two answers are computed from one lookup and cannot diverge.
 */
export function findRelease(log: Changelog, version: string): ChangelogRelease | undefined {
  return log.releases.find((release) => release.version === version);
}
